vehicle_command_adapter:
  ros__parameters:
    max_steering_angle: 0.6
    max_speed: 15.0

can_gateway:
  ros__parameters:
    can_interface: "can0"
    steering_can_id: 0x18
    throttle_can_id: 0x19
